---
title: "Welcome"
---

This site contains all the information you need for your computer
science course.

## Schedule

The schedule reflects the current state of planning. Changes are to be
expected during the course of the semester.

| Date | Topic |
| :--- | :--- |
| 20.08.2025 | Networks: TCP/IP |
| 27.08.2025 | Networks: Wireshark |
| 03.09.2025 | Networks: Exercise |
| 10.09.2025 | Cryptology: Caesar |
| 24.09.2025 | Cryptology: Vigenère Chiffre |
| 22.10.2025 | Test |
| 29.10.2025 | Cryptology: Break Vigenère |
| 05.11.2025 | [Cryptology: Symmetric encryption methods](files/lektionen_hs25/251105_symetricencryption/symetricencryption.html) |
| 12.11.2025 | [Cryptology: Symmetric encryption XOR](files/lektionen_hs25/251112_xorencryption/xorencryption.html) |
| 19.11.2025 | Lehrerfortbildung |
| 26.11.2025 | [Cryptology: Symmetric encryption AES](files/lektionen_hs25/251126_aesencryption/aesencryption.html) |
| 03.12.2025 | [Cryptology: Diffie-Hellmann](files/lektionen_hs25/251203_dh_rsa/deffiehellman.md) / [RSA Asymetric encryption](files/lektionen_hs25/251203_dh_rsa/rsaasymetricencryption.md) |
| 10.12.2025 | [Cryptology: Signature](files/lektionen_hs25/251210_signature/signatureexplained.md) |
| 17.12.2025 | [Test zu Cryptology](files/lektionen_hs25/251217_lk_ki/KannListe.md) / [anschl. Start mit AI](files/lektionen_hs25/251217_lk_ki/kiexplained.md)|
| 07.01.2026 | AI |
| 14.01.2026 | AI |
| 21.01.2026 | AI |




## Grading

Two written examinations are scheduled per semester. In addition,
oral participation is graded. Oral participation includes, in
particular, asking questions.  

The Final grades are calculated as a weighted average of the two.
written examinations and the oral participation grade. The
Average grade of the two written examinations is weighted at 90%, while
the grade for oral participation is weighted at 10%.

You have the opportunity to improve your mark in an upcoming exam. If
you report an issue through the link on the right-hand side before the
exam takes place, you may be awarded a maximum increase of one mark.  
To report an issue, you must sign up with
<a href="https://www.github.com" target="_blank">
GitHub</a>. Use your school email address to register.

## Appointments


If you would like a personal appointment, here is the link to 
<a href="https://calendar.app.google/UynTL5ttVPHhK1Hc8" target="_blank">
Rent-A-Mock</a>.