---
title: "13 Symetric encryption"
date: 2025-11-05
date-format: DD.MM.YYYY
author: "Peter Rutschmann"
---

## Symetrische Verschlüsselung

Bei der **symmetrischen Verschlüsselung** wird **derselbe Schlüssel** sowohl zum **Verschlüsseln** als auch zum **Entschlüsseln** einer Nachricht verwendet.

> Sender und Empfänger müssen denselben geheimen Schlüssel kennen und sicher austauschen.

Sie konnten bereits Erfahrungen mit den beiden Verfahren **Ceasar-** und **Viegenere-Verschlüsselung** machen.

- Beide Verfahren verwenden einen Schlüssel:
     - Ceasar-Verschlüsselung: Zahl: um wieviele Buchstaben das Alphabet verschoben wird.
     - Vigenere: Key-Wort: wie stark jeder Buchstabe einzeln verschoben wird.
- Bei beiden Verfahren werden die Buchstaben nach einer bestimmten Regeln durch andere Buchstaben ersetzt. Dies nennt man **Substitution**.

> Substitution bedeutet in der Kryptografie, dass Zeichen oder Bitmuster systematisch durch andere ersetzt werden – die Position bleibt gleich, nur der Inhalt ändert sich.

---

### Aufgabe warming up mit Ceasar

```text
Verschlüsselung: Ceasar
Alphabet: abcdefghijklmnopqrstuvwxyz
Key: 5
Verschlüsselter Text: fqxjwfltsfzkijwoflijnsjsgqfzjsxyjnsknsijy

Wie lautet der entschlüsselte Text?
```
::: {.callout-tip title="Lösung" collapse=true}
alseragonaufderjagdeinenblauensteinfindet

abcdefghijklmnopqrstuvwxyz
12345abcdefghijklmnopqrstuvwxyz
vwxyz

fqxjwflts...
alseragon --> als eragon
:::

---

### Aufgabe warming up mit Vigenere

```text
Verschlüsselung: Vigenere
Alphabet: abcdefghijklmnopqrstuvwxyz
Key: saphira
Verschlüsselter Text: shcaminacwalrskdxlavrxuckmznwssyithwntpmjswicsmsefvtyivnveguezrv

Wie lautet der entschlüsselte Text?
```
::: {.callout-tip title="Lösung" collapse=true}
ahnternichtdassdieserfundeinesdracheneiesseinlebenveraendernwird
:::

---

Die Caesar- und die Viegenere-Verschlüsselung lassen sich mit etwas Aufwand entschlüsseln, auch wenn man den Schlüssel nicht kennt.<br>
Nutzt man einen Computer, so dauert das Knacken des Codes Bruchteile von Sekunden.

Eine sichere Verschlüsselung muss also ein Verfahren anwenden, so dass man den verschlüsselten Inhalt ohne Kenntnisse des Schlüssels nicht innert nützlicher Zeit knacken kann.<br>
Das ist eine Herausforderung, deren sich Mathematiker annehmen.

## Symmetrische Verschlüsselungsverfahren in der Informatik

Für die Informatik, sind Caesar und Vigenère nicht geeignet.<br>
Computer können diese Codes in Sekunden durch Häufigkeitsanalyse oder Brute-Force entschlüsseln.

Mögliche symetrische Verschlüsselungsverfahren der Informatik sind:


| Verfahren                          | Beschreibung                                      | Autor                                   | Sicherheit                                         |
|:-----------------------------------|:--------------------------------------------------|:----------------------------------------|:---------------------------------------------------|
| 3DES (Triple DES)                  | Dreifache DES-Verschlüsselung                     | IBM (basiert auf DES)                   | Nicht mehr empfohlen (langsam, teilweise unsicher) |
| AES (Advanced Encryption Standard) | Blockcipher, heute globaler Standard              | Joan Daemen & Vincent Rijmen (Rijndael) | Sehr sicher (empfohlen)                            |
| Blowfish                           | Blockcipher, 64-bit Blockgröße                    | Bruce Schneier                          | Sicher, aber Blockgröße heute problematisch        |
| Camellia                           | AES-ähnliche Blockcipher                          | Mitsubishi & NICT Japan                 | Sehr sicher, weniger verbreitet                    |
| ChaCha20                           | Stromchiffre, modern & schnell                    | Daniel J. Bernstein                     | Sehr sicher, bevorzugt in TLS/HTTPS & VPNs         |
| DES (Data Encryption Standard)     | Blockcipher, 56-bit Schlüssel                     | IBM (mit NSA Einfluss)                  | Unsicher (zu kurzer Schlüssel)                     |
| IDEA                               | Blockcipher, 128-bit Schlüssel                    | Lai & Massey                            | Sicher, aber patentiert (lange Zeit)               |
| RC4                                | Stromchiffre                                      | Ronald Rivest                           | Unsicher (nicht mehr verwenden)                    |
| RC5                                | Blockcipher mit variabler Block- & Schlüssellänge | Ronald Rivest                           | Moderate Sicherheit (alt)                          |
| RC6                                | AES-Finalist, Blockcipher                         | Ronald Rivest, RSA Labs                 | Sicher, aber weniger verbreitet als AES            |
| Salsa20                            | Vorgänger von ChaCha20                            | Daniel J. Bernstein                     | Sehr sicher, performant                            |
| Serpent                            | Blockcipher, AES-Finalist                         | Ross Anderson, Eli Biham, Lars Knudsen  | Sehr sicher, aber langsamer als AES                |
| Twofish                            | Blockcipher, AES-Finalist                         | Bruce Schneier & Team                   | Sehr sicher, Alternative zu AES                    |

## Binäre Darstellung einer Nachricht

Alle digitalen Informationen sind binär.
Texte, Bilder, Audio – alles wird im Computer als Folge von Nullen und Einsen gespeichert und verarbeitet.

Digitale Verschlüsselungsverfahren arbeiten immer auf dieser binären Darstellung einer Nachricht – also auf Bits (0 und 1).<br>

> Bit: 0 oder 1<br>
> Nibble: 4 Bit: => 0000 bis 1111<br>
> Byte: 8 Bit:   => 0000'0000 bis 1111'1111 (Das ' Zeichen hilft beim Lesen)

Ein symetrisches Verschlüsselungsverfahren nimmt diese Bitfolgen als Eingabe (Klartext) und transformiert sie anhand des Schlüssel und seinem Algorythmus zu einer neuen Bitfolge (Geheimtext).

Ein Text muss also als erstes in eine binäre Zeichenfolge umgewandelt werden.

**Beispiel:**

```text
Klartext:         H       E        L        L        O
Binär (UTF8): 01001000 01000101 01001100 01001100 01001111

Verschlüsselt: 10111001 01101100 11010100 ...
```

### Binar versus Hexadezimal

Menschen können Hexwerte einfacher erkennen und vergleichen als lange Bitfolgen.<br>
Hexwerte sind Zahlen im 16er Format.<br>
Speicheradressen, Farbwerte, Zeichencodes und verschlüsselte Daten werden fast immer in Hex dargestellt.

```text
Buchstabe: A
UTF8-Code: 48 (hex), 72(dez), 01001000 (bin)
```

Die beiden Zeichen aus dem Hexwert entsprechen jeweils 4 Bit des Bytes.<br>
Damit lässt sich eine Bitfolge einfach in einen Hexfolge umrechnen. (und umgekehrt)

```text
  4    8
0100'1000
```
---

## Aufgabe Textzeichen als hexadezimaler Code

Welchem hexadezimalen Code entspricht das durchbare Zeichen B?<br>
Dies ist in einer Tabelle fix festgelegt.

Lesen Sie dazu: [Erklärung zu ASCII und UTF](chapter/ascii_utf.html)

---

## Aufgabe HEX-Code entschlüsseln

Erinnern Sie sich noch? ... bei Ceasar und Vigenere werden Buchstaben nach einer bestimmten Regel durch andere ersetzt. Eine Substitution wird auch bei UTF8 angewandt. Allerdings ist der Schlüssel (UTF8 Codiertabelle) allen zugänglich.. eine Verschlüsselung ist es nicht.<br>
[Liste der UTF8 Codierung](https://www.utf8-chartable.de/)

```text
Verschlüsselung: UTF()
Key: https://www.utf8-chartable.de/
Verschlüsselter Text: 65 69 6e 65 73 63 68 69 63 6b 73
 61 6c 68 61 66 74 65 77 65 6c 74 76 6f 6c 6c 65 72 6d
 61 67 69 65 75 6e 64 64 75 6e 6b 6c 65 72 6d 61 65 63
 68 74 65

Wie lautet der entschlüsselte Text?
```
::: {.callout-tip title="Lösung" collapse=true}
eineschicksalhafteweltvollermagieunddunklermaechte
:::

<h5 id="digitale-verschluesselung-mit-xor"></h5>

## Digitale Verschlüsselung mit XOR

Es wird Zeit für ein erstes digitales Verschlüsselungsverfahren.<br>
Lesen und lösen Sie dazu:

<a href="https://skriptenmk.github.io/I_eW_24-28/files/lektionen_hs25/251105_symetricencryption/chapter/HEXtoBIN.txt" 
   download="HEXtoBIN.txt">
   Umrechung HEX to BIN herunterladen
</a>

<a href="https://skriptenmk.github.io/I_eW_24-28/files/lektionen_hs25/251105_symetricencryption/chapter/xor_encryption.ipynb" 
   download="xor_encryption.ipynb">
   Notebook zu XOR herunterladen
</a>

<h5 id="digitale-verschluesselung-mit-aes"></h5>

## Verfahren der digitalen Verschlüsselung

Die Techniken der digitalen Verschlüsselung lassen sich unter _Transformation_ als Oberbegriff zusammenfassen.

Eine Transformation kann aus diesens Schritten bestehen:

- **Substitution** : Ersetzen von Symbolen durch andere Symbole
- **Transposition/Permutation** : Vertauschung von Zeichen oder Bits

- **Diffusion** : Streuung der Klartext-Information über viele Bits im Geheimtext
- **Konfusion** : Komplexe, nichtlineare Beziehung zwischen Schlüssel und Geheimtext
- **Rundensystem** : Mehrfache Wiederholung von Substitution und Permutation
- **Key Schedule** : Algorithmus zur Ableitung von Rundenschlüsseln :
- **Blockchiffre** | Verschlüsselt Daten blockweise (z. B. 128 Bit bei AES)
- **Stromchiffre** | Verschlüsselt Bit für Bit oder Byte für Byte

### Substitution

- UTF8 wendet Substituation an, es ersetzt anhand der UTF8 Code-Tabled ein Buchstabe durch eine Bitfolge
- **XOR** wendet Substitution an, es ersetzt die Bits auf Grund des Schlüssel durch andere Bits.

### Transposition/Permutation

A = 01000001<br>
key = 3

Meine eigene Regel:

- Buchstabencodierung UTF8, nur 7-Bit Buchstaben.
- Rechtes, fehlende Bit mit 1 auffüllen
- Teile die Bitfolge in Gruppen von 3 bit. Ergänze die Folge mit 1, falls es nicht aufgeht.
- Innerhalb jeder 3er-Gruppe vertauschen wir die Positionen nach Muster (1,2,3) -> (3,1,2)

```text
010 000 01 A
010 000 011  auffüllen
001 000 101 (1,2,3) -> (3,1,2)

Auflösen:
001 000 101 
010 000 011 (1,2,3) -> (3,2,1)
010 000 01  A
```

## Aufgabe Anwenden Transponieren

- Wenden Sie die obige Transposition auf einen 4 stellige Dezimale Zahl an.
- Wandeln Sie die Zifferen der Zahl mit UTF8 in eine binäre Zahlenfolge um. (ergibt 4 Bytes)<br/>
  [Liste der UTF8 Codierung](https://www.utf8-chartable.de/)
- Transponieren Sie mit dem key=3 gemäss obiger Regel
- Tauschen Sie das Ergebnis mit Ihrem Lernpartner aus, findet er die ursprüngliche Zahl heraus?

## Aufgabe Anwenden eines mehrfachen Transponieren

- ausprobieren: [Permutation-Demo](chapter/permutation_demo.html)
- analysieren Sie die Schritte
- notieren Sie die Schritte auf.
- Codieren Sie einen von Ihnen gewählten Buchstaben.
     - Buchstabe mit UTF8 Tabelle in Bits umwandeln.
     - In der Permutations-Demo codieren, eigenen Schlüssel und Anzahl Runden wählen.
     - Mit Lernpartner Codierten Code, Schlüssel und Anzahl Runden austauschen.
     - Kann Ihr Lernpartner den richtigen Buchstaben herausfinden?

## Anwendung in der Praxis mit Beispiel AES Verschlüsselung

### AES Verfahren

**AES** ist ein modernes Verschlüsselungsverfahren.<br>
AES verschlüsselt, indem es den Klartext blockweise (128 Bit) in mehreren Runden mit dem Schlüssel verarbeitet.<br>
In jeder Runde passieren vier Schritte:

- Substitution: SubBytes -> jedes Byte wird durch die S-Box ersetzt 
- Permutation: ShiftRows -> die Zeilen werden verschoben
- Diffusion: MixColumns -> die Spalten werden gemischt.
- AddRoundKey → der Block wird mit dem Rundenschlüssel per XOR verknüpft.
- Nach 10 (12 / 14) Runden entsteht der Geheimtext.

### AES Verfahren Demo

Das sind einige Schritte. Die [_AWS web demo_](https://jrvidal.github.io/aes-demo/) zeigt das anschaulich.

- Link anklicken, Random wählen, die Schritte beobachten.
- Das Resultat auch wieder dekodieren.

Eine [AES-Animation](https://legacy.cryptool.org/en/cto/aes-animation), die das Verfahren versucht zu verdeutlichen.

- Probieren Sie es aus.

### AES selber anwenden

Laden Sie das Notebook herunter, um AES praktisch anzuwenden.<br>
Lesen und lösen Sie:

<a href="https://skriptenmk.github.io/I_eW_24-28/files/lektionen_hs25/251105_symetricencryption/chapter/aes_encryption.ipynb" 
   download="aes_encryption.ipynb">
   Notebook zu AES herunterladen
</a>